#!/bin/bash
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_CHOREONOID_EXECUTABLE=OFF -DUSE_PYTHON3=OFF -DBUILD_SCENE_EFFECTS_PLUGIN=ON -DBUILD_MULTICOPTER_PLUGIN=ON -DBUILD_MULTICOPTER_SAMPLES=ON -DBUILD_COMPETITION_PLUGIN=ON -DENABLE_GUI=ON -DBUILD_HAIRO_WORLD_PLUGIN=ON -DBUILD_RTF_TEST_PLANT=ON -DENABLE_INSTALL_RPATH_USE_LINK_PATH=ON
